# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: istio-infrastructure
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/simoneroselli/platform-engineer-gateway-api.git
#     targetRevision: HEAD
#     path: platform-workloads/infrastructure/istio-system
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: istio-system
#   syncPolicy:
#     automated: { prune: true, selfHeal: true }
#     syncOptions: [CreateNamespace=true, ServerSideApply=true]

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/simoneroselli/platform-engineer-gateway-api.git
    targetRevision: HEAD
    path: platform-workloads/infrastructure/gateways
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: v28.0.0
    helm:
      values: |
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesGateway:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators-task-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/simoneroselli/platform-engineer-gateway-api.git'
    targetRevision: HEAD
    path: platform-workloads/operators/wordsmith-ops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: processing-pipeline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true