apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-workloads-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            valuesFile: platform-workloads/environments/dev/values.yaml
            namespace: wordsmith-dev-app
          - env: prod
            valuesFile: platform-workloads/environments/prod/values.yaml
            namespace: wordsmith-prod-app
  template:
    metadata:
      name: 'wordsmith-{{env}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/simoneroselli/platform-engineer-gateway-api.git'
        targetRevision: HEAD
        path: platform-workloads/charts/wordsmith
        helm:
          valueFiles:
            - /{{valuesFile}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true