apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "wordsmith.fullname" . }}-api'
  namespace: '{{ .Values.namespace | default "wordsmith-app" }}'
spec:
  replicas: '{{ .Values.api.replicaCount }}'
  selector:
    matchLabels:
      app: '{{ include "wordsmith.fullname" . }}-api'
  template:
    metadata:
      labels:
        app: '{{ include "wordsmith.fullname" . }}-api'
    spec:
      containers:
      - name: api
        image: '{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}'
        ports:
        - containerPort: 8080