apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ include "wordsmith.fullname" . }}-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ include "wordsmith.fullname" . }}-api