apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: '{{ .Values.namespace | default "wordsmith-app" }}'
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: '{{ include "wordsmith.fullname" . }}-api'