apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.appFullname }}-api'
  namespace: '{{ .Values.appFullname }}'
spec:
  replicas: {{ .Values.app.api.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Values.appFullname }}-api'
  template:
    metadata:
      labels:
        app: '{{ .Values.appFullname }}-api'
    spec:
      containers:
      - name: '{{ .Values.appFullname }}-api'
        image: '{{ .Values.app.api.image.repository }}:{{ .Values.app.api.image.tag }}'
        ports:
        - containerPort: 8080