apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.appFullname }}-db'
  namespace: '{{ .Values.appFullname }}'
spec:
  replicas: {{ .Values.app.database.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Values.appFullname }}-db'
  template:
    metadata:
      labels:
        app: '{{ .Values.appFullname }}-db'
    spec:
      containers:
      - name: db
        image: '{{ .Values.app.database.image.repository }}:{{ .Values.app.database.image.tag }}'
        ports:
        - containerPort: 5432