apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordsmith.fullname" . }}-db
  namespace: {{ include "wordsmith.fullname" . }}-app
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordsmith.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "wordsmith.fullname" . }}-db
    spec:
      containers:
      - name: db
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        ports:
        - containerPort: 5432