apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values appFullname }}-db'
  namespace: '{{ .Values appFullname }}'
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: '{{ .Values appFullname }}-db'