apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.appFullname }}-web'
  namespace: '{{ .Values.appFullname }}'
spec:
  replicas: {{ .Values.app.web.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Values.appFullname }}-web'
  template:
    metadata:
      labels:
        app: '{{ .Values.appFullname }}-web'
    spec:
      containers:
      - name: web
        image: '{{ .Values.app.web.image.repository }}:{{ .Values.app.web.image.tag }}'
        ports:
        - containerPort: 80
        env:
        - name: API_HOST
          value: "wordsmith-api:80"