apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordsmith.fullname" . }}-web
  namespace: {{ .Values.namespace | default "wordsmith-app" }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordsmith.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "wordsmith.fullname" . }}-web
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: API_HOST
          value: "wordsmith-api:80"