apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- db-dns-alias.yaml
- wordsmith-web-deployment.yaml
- wordsmith-api-deployment.yaml
- wordsmith-db-deployment.yaml