apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-api
  namespace: wordsmith-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsmith-api
  template:
    metadata:
      labels:
        app: wordsmith-api
    spec:
      containers:
      - name: api
        image: dockersamples/wordsmith-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wordsmith-api
  namespace: wordsmith-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: wordsmith-api