apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-db
  namespace: wordsmith-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsmith-db
  template:
    metadata:
      labels:
        app: wordsmith-db
    spec:
      containers:
      - name: db
        image: dockersamples/k8s-wordsmith-db:latest
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: wordsmith-db
  namespace: wordsmith-app
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: wordsmith-db