apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-engine
  namespace: processing-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-engine
  template:
    metadata:
      labels:
        app: api-engine
    spec:
      containers:
      - name: engine
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"