# environments/dev/values.yaml
namespace: wordsmith-dev-app
version: 0.1.0
web:
  replicaCount: 1  # Scale out for production
api:
  replicaCount: 1
database:
  host: "wordsmith-db.wordsmith-dev-app.svc.cluster.local"