web:
  replicaCount: 1
  image: "dockersamples/k8s-wordsmith-web:latest"
api:
  replicaCount: 1
  image: "dockersamples/k8s-wordsmith-api:latest"
db:
  replicaCount: 1
  image: "dockersamples/k8s-wordsmith-db:latest"