# environments/prod/values.yaml
namespace: wordsmith-prod-app
version: 0.2.0
web:
  replicaCount: 3  # Scale out for production
api:
  replicaCount: 3
database:
  host: "wordsmith-db.wordsmith-prod-app.svc.cluster.local"