# environments/prod/values.yaml
namespace: wordsmith-prod-app
version: 0.2.0
ingress:
  stable:
    path: "/"
    host: "wordsmith.local"
  canary:
    path: "/"
    host: "wordsmith.local"
    canary: "true"
    canary_weight: "10"
web:
  replicaCount: 1  # Scale out for production
api:
  replicaCount: 1
database:
  host: "wordsmith-db.wordsmith-prod-app.svc.cluster.local"