# environments/prod/values.yaml
namespace: wordsmith-prod-app
version: 0.2.0
web:
  replicaCount: 1  # Scale out for production
api:
  replicaCount: 1
database:
  host: "wordsmith-db.wordsmith-prod-app.svc.cluster.local"