apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordsmith-operator-sa
  namespace: wordsmith-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordsmith-operator-role
rules:
  - apiGroups: ["padre.maronno"]
    resources: ["wordsmithapps"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wordsmith-operator-binding
subjects:
  - kind: ServiceAccount
    name: wordsmith-operator-sa
    namespace: wordsmith-app
roleRef:
  kind: ClusterRole
  name: wordsmith-operator-role
  apiGroup: rbac.authorization.k8s.io