# Global/Default values
namespace: wordsmith-app
fullname: wordsmith

web:
  replicaCount: 1
  image:
    repository: dockersamples/k8s-wordsmith-web:latest
    tag: latest

api:
  replicaCount: 1
  image:
    repository: dockersamples/k8s-wordsmith-api:latest
    tag: latest

db:
  replicaCount: 1
  image:
    repository: dockersamples/k8s-wordsmith-db
    tag: latest