# Global/Default values
gatewayFullname: wordsmith-gateway
gatewayNamespace: traefik-system
app:
  web:
    replicaCount: 1
    image:
      repository: dockersamples/k8s-wordsmith-web
      tag: latest

  api:
    replicaCount: 1
    image:
      repository: dockersamples/k8s-wordsmith-api
      tag: latest

  database:
    replicaCount: 1
    host: "localhost"
    image:
      repository: dockersamples/k8s-wordsmith-db
      tag: latest