apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: wordsmith-gateway
  namespace: wordsmith-gateway-api
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.wordsmith.local"
    allowedRoutes:
      namespaces:
        from: All