name: Helm Validate and Template Check

on:
  push:
    branches: [ "main" ]

jobs:
  validate-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Lint Helm Chart with Values
        run: |
          echo "Linting Wordsmith chart with development values..."
          helm lint platform-workloads/charts/wordsmith -f platform-workloads/environments/dev/values.yaml
          
          echo "Linting Wordsmith chart with production values..."
          helm lint platform-workloads/charts/wordsmith -f platform-workloads/environments/prod/values.yaml

      - name: Silent Template Rendering Check (Dev)
        run: |
          echo "Checking dev template compilation..."
          helm template wordsmith-dev-app platform-workloads/charts/wordsmith \
            -f platform-workloads/environments/dev/values.yaml \
            --namespace wordsmith-dev-app > /dev/null

      - name: Silent Template Rendering Check (Prod)
        run: |
          echo "Checking prod template compilation..."
          helm template wordsmith-prod platform-workloads/charts/wordsmith \
            -f platform-workloads/environments/prod/values.yaml \
            --namespace wordsmith-prod-app > /dev/null
  
  validate-operator:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform-workloads/operators/wordsmith-ops
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r platform-workloads/operators/wordsmith-ops/requirements.txt
          python -m pip install --upgrade pip
      
      # - name: Install Dependencies 2
      #   run: |
      #     pip install -r platform-workloads/operators/wordsmith-ops/requirements.txt
      #     pip install flake8 safety

      # - name: Lint Python Code (Flake8)
      #   working-directory: platform-workloads/operators/wordsmith-ops
      #   run: |
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # - name: Check Python Dependencies for Vulnerabilities (Safety)
      #   working-directory: platform-workloads/operators/wordsmith-ops
      #   run: |
      #     safety check -r requirements.txt || true